import type { Metadata } from "next";
import type { ReactNode } from "react";

// Styles:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Fonts:
import { fontSans, fontMono, fontHeadings } from "@/styles/fonts";

// Providers:
import { ThemeProvider } from "@/providers/themeProvider";

// Metadata:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${fontSans.variable} ${fontHeadings.variable} ${fontMono.variable}`,
          "bg-zinc-50 dark:bg-zinc-900",
          "text-zinc-950 dark:text-zinc-50",
          "font-sans antialiased",
          "overscroll-none",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
