import type { Metadata } from "next";
import type { ReactNode } from "react";

// Styles:
import "@/styles/globals.css";
import { fontMono, fontSans } from "@/components/ui/fonts";
import { cn } from "@/utils/cn";

// Providers:
import { ThemeProvider } from "@/providers/themeProvider";

// Metadata:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${fontSans.variable} ${fontMono.variable}`,
          "font-sans antialiased",
          "bg-neutral-100 dark:bg-neutral-900",
          "text-neutral-900 dark:text-neutral-50",
          "scroll-smooth"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
