import type { Metadata } from "next";
import type { ReactNode } from "react";

// Styles:
import "@/styles/globals.css";
import { fontMono, fontSans } from "@/components/ui/fonts";
import { cn } from "@/utils/cn";

// Providers:
import { ThemeProvider } from "@/providers/themeProvider";
import Sidebar from "@/components/layout/sidebar";

// Metadata:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${fontSans.variable} ${fontMono.variable}`,
          "font-sans antialiased",
          "bg-neutral-50 dark:bg-neutral-900",
          "text-black dark:text-white",
          "selection:bg-neutral-200 selection:text-neutral-900 dark:selection:bg-neutral-800 dark:selection:text-neutral-50",
          "scroll-smooth",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar />
          <main className={cn("container mx-auto max-w-3xl py-12")}>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
